// Code generated by MockGen. DO NOT EDIT.
// Source: src/gdpr_mcp_server_dal/gdpr_data_client_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/gdpr_mcp_server_dal/gdpr_data_client_interface.go -destination=tests/gdpr_mcp_server_dal_mocks/gdpr_data_client_mock.go -package=gdpr_mcp_server_dal_mocks
//

// Package gdpr_mcp_server_dal_mocks is a generated GoMock package.
package gdpr_mcp_server_dal_mocks

import (
	reflect "reflect"

	models "github.com/6022-labs/gdpr-mcp-server/src/gdpr_mcp_server/models"
	gomock "go.uber.org/mock/gomock"
)

// MockGdprDataClientInterface is a mock of GdprDataClientInterface interface.
type MockGdprDataClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGdprDataClientInterfaceMockRecorder
	isgomock struct{}
}

// MockGdprDataClientInterfaceMockRecorder is the mock recorder for MockGdprDataClientInterface.
type MockGdprDataClientInterfaceMockRecorder struct {
	mock *MockGdprDataClientInterface
}

// NewMockGdprDataClientInterface creates a new mock instance.
func NewMockGdprDataClientInterface(ctrl *gomock.Controller) *MockGdprDataClientInterface {
	mock := &MockGdprDataClientInterface{ctrl: ctrl}
	mock.recorder = &MockGdprDataClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGdprDataClientInterface) EXPECT() *MockGdprDataClientInterfaceMockRecorder {
	return m.recorder
}

// ArticleParagraphsSetSnapshot mocks base method.
func (m *MockGdprDataClientInterface) ArticleParagraphsSetSnapshot() map[string][]*models.ArticleParagraph {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArticleParagraphsSetSnapshot")
	ret0, _ := ret[0].(map[string][]*models.ArticleParagraph)
	return ret0
}

// ArticleParagraphsSetSnapshot indicates an expected call of ArticleParagraphsSetSnapshot.
func (mr *MockGdprDataClientInterfaceMockRecorder) ArticleParagraphsSetSnapshot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArticleParagraphsSetSnapshot", reflect.TypeOf((*MockGdprDataClientInterface)(nil).ArticleParagraphsSetSnapshot))
}

// ArticlesSetSnapshot mocks base method.
func (m *MockGdprDataClientInterface) ArticlesSetSnapshot() map[string]*models.Article {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArticlesSetSnapshot")
	ret0, _ := ret[0].(map[string]*models.Article)
	return ret0
}

// ArticlesSetSnapshot indicates an expected call of ArticlesSetSnapshot.
func (mr *MockGdprDataClientInterfaceMockRecorder) ArticlesSetSnapshot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArticlesSetSnapshot", reflect.TypeOf((*MockGdprDataClientInterface)(nil).ArticlesSetSnapshot))
}

// ChaptersSetSnapshot mocks base method.
func (m *MockGdprDataClientInterface) ChaptersSetSnapshot() map[string]*models.Chapter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChaptersSetSnapshot")
	ret0, _ := ret[0].(map[string]*models.Chapter)
	return ret0
}

// ChaptersSetSnapshot indicates an expected call of ChaptersSetSnapshot.
func (mr *MockGdprDataClientInterfaceMockRecorder) ChaptersSetSnapshot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChaptersSetSnapshot", reflect.TypeOf((*MockGdprDataClientInterface)(nil).ChaptersSetSnapshot))
}

// RecitalsSetSnapshot mocks base method.
func (m *MockGdprDataClientInterface) RecitalsSetSnapshot() map[string]*models.Recital {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecitalsSetSnapshot")
	ret0, _ := ret[0].(map[string]*models.Recital)
	return ret0
}

// RecitalsSetSnapshot indicates an expected call of RecitalsSetSnapshot.
func (mr *MockGdprDataClientInterfaceMockRecorder) RecitalsSetSnapshot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecitalsSetSnapshot", reflect.TypeOf((*MockGdprDataClientInterface)(nil).RecitalsSetSnapshot))
}
